In [5]:
import pandas as pd

## Opens .conllu output for language classifier comparisons 
## Hindi basq

with open("results/latest_run/hi_hdtb-ud_eu_bdt-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df1 = pd.DataFrame([sub.split(",") for sub in read_file])
df1.head(5)

# new_header1 = df1.iloc[0] 
# df1 = df1[1:] 
# df1.columns = new_header1 
# df1["probability_A"] = pd.to_numeric(df1["probability_A"], errors='coerce')
# df1["probability_A"].mean()

df_roles = df1[[1,7]]
roles_header = df_roles.iloc[0]
df_roles = df_roles[1:]
df_roles.columns = roles_header
df_roles

df1_predict_acc = df_roles.apply(lambda row: all(i in row.predicted_role for i in row.role), axis=1)
#df1_predict_acc.value_counts()
#Prediction matches over all layers True = 13243 (0.50934), False = 12757 (0.4906)

#df1.to_csv('df1.csv', index=False)

<class 'list'>

In [3]:
## Hindi Indo

with open("results/latest_run/hi_hdtb-ud_id_gsd-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df2 = pd.DataFrame([sub.split(",") for sub in read_file])
df2.head(15)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,,,serangan,terjadi,,O,0.002978764707222581,12,0.88996138996139,0.8623326959847036\n
2,1,O,,,,bakar,rumah,O,0.014411342330276966,12,0.88996138996139,0.8623326959847036\n
3,2,O,,,,memenggal,penghuni,O,0.004825534299015999,12,0.88996138996139,0.8623326959847036\n
4,3,S-passive,,,Perkembangan,ikut,,A,0.9930665493011475,12,0.88996138996139,0.8623326959847036\n
5,4,A,,,kapal,tembak,salvo,A,0.9696663618087769,12,0.88996138996139,0.8623326959847036\n
6,5,O,,,,tembak,salvo,O,0.001937231281772256,12,0.88996138996139,0.8623326959847036\n
7,6,O,,,,sarang,torpedo,O,0.009647766128182411,12,0.88996138996139,0.8623326959847036\n
8,7,O,,,,parah,kerusakan,O,0.007169482763856649,12,0.88996138996139,0.8623326959847036\n
9,8,S-passive,,,Pasukan,siasat,,A,0.9999958276748657,12,0.88996138996139,0.8623326959847036\n
10,9,A,,,Krogh,buat,studi,A,0.999998927116394,12,0.88996138996139,0.8623326959847036\n
11,10,O,,,,buat,studi,O,3.454772740951739e-05,12,0.88996138996139,0.8623326959847036\n
12,11,S-passive,,,Lagu,tampil,,O,0.006776544731110334,12,0.88996138996139,0.8623326959847036\n
13,12,S-passive,,,gerakan,mulai,,O,0.11954818665981293,12,0.88996138996139,0.8623326959847036\n
14,13,O,,,,bentuk,kelompok,O,0.07112119346857071,12,0.88996138996139,0.8623326959847036\n

In [19]:
## Hindi mara

with open("results/latest_run/hi_hdtb-ud_mr_ufal-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df3 = pd.DataFrame([sub.split(",") for sub in read_file])
df3.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,A,Nom,,राजा,करित,त्याला,A,1.0,12,0.88996138996139,0.8623326959847036\n
2,1,S,Nom,,राजा,म्हणणे,,A,0.9999496936798096,12,0.88996138996139,0.8623326959847036\n
3,2,S,Nom,,टक्केटोणपे,खाणे,,O,0.17719615995883942,12,0.88996138996139,0.8623326959847036\n
4,3,A,Erg,,राजाने,सांगणे,विचार,A,0.9999946355819702,12,0.88996138996139,0.8623326959847036\n

In [25]:
## Hindi ukr

with open("results/latest_run/hi_hdtb-ud_uk_iu-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df4 = pd.DataFrame([sub.split(",") for sub in read_file])
df4.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,Nom,Inan,фреска,бути,,A,0.918612003326416,12,0.88996138996139,0.8623326959847036\n
2,1,S,Nom,Anim,одновірці,зібратися,,A,0.9943737983703613,12,0.88996138996139,0.8623326959847036\n
3,2,O,Acc,Inan,,замазувати,стіну,O,0.0009756358340382576,12,0.88996138996139,0.8623326959847036\n
4,3,O,Acc,Inan,,знищити,мальовидло,O,0.194249227643013,12,0.88996138996139,0.8623326959847036\n

In [26]:
## Hindi urdu

with open("results/latest_run/hi_hdtb-ud_ur_udtb-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df5 = pd.DataFrame([sub.split(",") for sub in read_file])
df5.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,Nom,,اجلاس,ہو,,O,0.003561136545613408,12,0.88996138996139,0.8623326959847036\n
2,1,S,Nom,,بورڈ,کر,,A,0.9438534379005432,12,0.88996138996139,0.8623326959847036\n
3,2,O,Nom,,,کر,اپیل,O,0.0025441960897296667,12,0.88996138996139,0.8623326959847036\n
4,3,A,Acc,,بورڈ,کروا,اپیلیں,A,1.0,12,0.88996138996139,0.8623326959847036\n

In [27]:
## Hindi hindi (exp 1?)

with open("results/latest_run/hi_hdtb-ud_hi_hdtb-ud-test.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df6 = pd.DataFrame([sub.split(",") for sub in read_file])
df6.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,O,Nom,,,खुल,पट,O,4.512222915309394e-07,12,0.88996138996139,0.8623326959847036\n
2,1,S,Acc,,पार्वती,कर,,A,0.9999996423721313,12,0.88996138996139,0.8623326959847036\n
3,2,O,Acc,,,पा,महादेव,O,2.9772260745630774e-07,12,0.88996138996139,0.8623326959847036\n
4,3,S,Nom,,धूनी,जल,,O,0.003478792728856206,12,0.88996138996139,0.8623326959847036\n

In [28]:
## basque indo

with open("results/latest_run/eu_bdt-ud_id_gsd-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df7 = pd.DataFrame([sub.split(",") for sub in read_file])
df7.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,,,serangan,terjadi,,A,0.8681724667549133,12,0.8652694610778443,0.8185880250223414\n
2,1,O,,,,bakar,rumah,O,8.161691198438348e-07,12,0.8652694610778443,0.8185880250223414\n
3,2,O,,,,memenggal,penghuni,O,0.35661888122558594,12,0.8652694610778443,0.8185880250223414\n
4,3,S-passive,,,Perkembangan,ikut,,A,0.9529194235801697,12,0.8652694610778443,0.8185880250223414\n

In [29]:
## basque mara

with open("results/latest_run/eu_bdt-ud_mr_ufal-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df8 = pd.DataFrame([sub.split(",") for sub in read_file])
df8.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,A,Nom,,राजा,करित,त्याला,A,0.9872235059738159,12,0.8652694610778443,0.8185880250223414\n
2,1,S,Nom,,राजा,म्हणणे,,A,0.6848072409629822,12,0.8652694610778443,0.8185880250223414\n
3,2,S,Nom,,टक्केटोणपे,खाणे,,A,0.8198820352554321,12,0.8652694610778443,0.8185880250223414\n
4,3,A,Erg,,राजाने,सांगणे,विचार,A,0.9896479249000549,12,0.8652694610778443,0.8185880250223414\n

In [30]:
## basque ukr

with open("results/latest_run/eu_bdt-ud_uk_iu-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df9 = pd.DataFrame([sub.split(",") for sub in read_file])
df9.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,Nom,Inan,фреска,бути,,A,0.9561126232147217,12,0.8652694610778443,0.8185880250223414\n
2,1,S,Nom,Anim,одновірці,зібратися,,A,0.9988012313842773,12,0.8652694610778443,0.8185880250223414\n
3,2,O,Acc,Inan,,замазувати,стіну,O,7.054072193568572e-05,12,0.8652694610778443,0.8185880250223414\n
4,3,O,Acc,Inan,,знищити,мальовидло,O,0.005626329220831394,12,0.8652694610778443,0.8185880250223414\n

In [31]:
## basque urdu

with open("results/latest_run/eu_bdt-ud_ur_udtb-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df10 = pd.DataFrame([sub.split(",") for sub in read_file])
df10.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,Nom,,اجلاس,ہو,,A,0.7131028175354004,12,0.8652694610778443,0.8185880250223414\n
2,1,S,Nom,,بورڈ,کر,,A,0.98117595911026,12,0.8652694610778443,0.8185880250223414\n
3,2,O,Nom,,,کر,اپیل,O,0.0006704188417643309,12,0.8652694610778443,0.8185880250223414\n
4,3,A,Acc,,بورڈ,کروا,اپیلیں,A,1.0,12,0.8652694610778443,0.8185880250223414\n

In [32]:
## basque basq

with open("results/latest_run/eu_bdt-ud_eu_bdt-ud-test.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df11 = pd.DataFrame([sub.split(",") for sub in read_file])
df11.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,Par,,hazkunderik,antzeman,,O,1.258978863916127e-05,12,0.8652694610778443,0.8185880250223414\n
2,1,S,,,agintari,ziurtatu,,A,0.9999855756759644,12,0.8652694610778443,0.8185880250223414\n
3,2,O,,,,onartu,eskari,O,0.0006036483682692051,12,0.8652694610778443,0.8185880250223414\n
4,3,S,,,hegazkin,egon,,A,0.9946459531784058,12,0.8652694610778443,0.8185880250223414\n

In [33]:
## urdu basq

with open("results/latest_run/ur_udtb-ud_eu_bdt-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df12 = pd.DataFrame([sub.split(",") for sub in read_file])
df12.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n,None
1,0,O,Abs,Inan,,jarri,masa,O,4.482377335079946e-06,12,0.8825757575757576,0.8375\n,None
2,1,O,,,,eman,herri,O,0.006065746769309044,12,0.8825757575757576,0.8375\n,None
3,2,O,,,,eman,laguntza,O,6.945942004676908e-06,12,0.8825757575757576,0.8375\n,None
4,3,O,,,,indartu,erakunde,O,0.009737110696732998,12,0.8825757575757576,0.8375\n,None

In [34]:
## urdu indo

with open("results/latest_run/ur_udtb-ud_id_gsd-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df13 = pd.DataFrame([sub.split(",") for sub in read_file])
df13.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,,,serangan,terjadi,,A,0.764359712600708,12,0.8825757575757576,0.8375\n
2,1,O,,,,bakar,rumah,A,0.9891718029975891,12,0.8825757575757576,0.8375\n
3,2,O,,,,memenggal,penghuni,A,0.9991132616996765,12,0.8825757575757576,0.8375\n
4,3,S-passive,,,Perkembangan,ikut,,A,0.5860880017280579,12,0.8825757575757576,0.8375\n

In [35]:
## urdu mara

with open("results/latest_run/ur_udtb-ud_mr_ufal-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df14 = pd.DataFrame([sub.split(",") for sub in read_file])
df14.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,A,Nom,,राजा,करित,त्याला,A,0.9999998807907104,12,0.8825757575757576,0.8375\n
2,1,S,Nom,,राजा,म्हणणे,,A,0.9766058921813965,12,0.8825757575757576,0.8375\n
3,2,S,Nom,,टक्केटोणपे,खाणे,,O,0.0001334912667516619,12,0.8825757575757576,0.8375\n
4,3,A,Erg,,राजाने,सांगणे,विचार,A,0.9999974966049194,12,0.8825757575757576,0.8375\n

In [36]:
## urdu ukr

with open("results/latest_run/ur_udtb-ud_uk_iu-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df15 = pd.DataFrame([sub.split(",") for sub in read_file])
df15.head(5)

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S,Nom,Inan,фреска,бути,,A,0.9975090026855469,12,0.8825757575757576,0.8375\n
2,1,S,Nom,Anim,одновірці,зібратися,,O,0.12039223313331604,12,0.8825757575757576,0.8375\n
3,2,O,Acc,Inan,,замазувати,стіну,O,0.0004212659550830722,12,0.8825757575757576,0.8375\n
4,3,O,Acc,Inan,,знищити,мальовидло,O,0.0581413209438324,12,0.8825757575757576,0.8375\n

In [12]:
import pandas as pd

with open("results/latest_run/fr_gsd-ud_he_iahltwiki-ud-train.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df16 = pd.DataFrame([sub.split(",") for sub in read_file])

df16

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,S-passive,,,מטופל,הוערך,,A,0.9990155696868896,12,0.9587628865979382,0.9293286219081273\n
2,1,A,,,סיכום,היווה,הערכה,A,0.9991753697395325,12,0.9587628865979382,0.9293286219081273\n
3,2,O,,,,היווה,הערכה,A,0.7488523721694946,12,0.9587628865979382,0.9293286219081273\n
4,3,S,,,תוצאת,סייע,,A,0.9988401532173157,12,0.9587628865979382,0.9293286219081273\n
...,...,...,...,...,...,...,...,...,...,...,...,...
25996,25995,A,,,שירות,פתח,מהדורות,O,0.2856890559196472,0,0.7216494845360825,0.8162544169611308\n
25997,25996,O,,,,פתח,מהדורות,O,0.2805440425872803,0,0.7216494845360825,0.8162544169611308\n
25998,25997,A,,,רצף,ייצג,קוד,A,0.9875854253768921,0,0.7216494845360825,0.8162544169611308\n
25999,25998,O,,,,ייצג,קוד,O,0.06823062896728516,0,0.7216494845360825,0.8162544169611308\n
26000,25999,S,,,כתיבת,ארך,,A,0.9995648264884949,0,0.7216494845360825,0.8162544169611308\n