In [2]:
import pandas as pd

In [5]:
### Testing out a function before looping through all of them


with open("de_gsd-ud_de_gsd-ud-test.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df = pd.DataFrame([sub.split(",") for sub in read_file])
df

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,O,Acc,,,machen,OWD,O,1.0426391781948041e-05,12,0.8455598455598455,0.8731182795698925\n
2,1,O,Acc,,,gefallen,Tauchen,O,0.2934567630290985,12,0.8455598455598455,0.8731182795698925\n
3,2,O,Acc,,,dranhängen,AOWD,O,0.0028503146022558212,12,0.8455598455598455,0.8731182795698925\n
4,3,O,Nom,,,machen,Termin,O,1.510456877440447e-05,12,0.8455598455598455,0.8731182795698925\n
...,...,...,...,...,...,...,...,...,...,...,...,...
14192,14191,O,Acc,,,beschlagnahmen,Mittel,A,0.8412541747093201,0,0.722007722007722,0.6731182795698925\n
14193,14192,A,Nom,,Sicherheitsagenten,nehmen,Platz,O,0.20422163605690002,0,0.722007722007722,0.6731182795698925\n
14194,14193,O,Acc,,,nehmen,Platz,O,0.28565987944602966,0,0.722007722007722,0.6731182795698925\n
14195,14194,S,Nom,,Präsident,scheinen,,A,0.9996484518051147,0,0.722007722007722,0.6731182795698925\n
14196,14195,O,Acc,,,vermissen,Stimme,O,0.0021522892639040947,0,0.722007722007722,0.6731182795698925\n

In [10]:
### Filter to the relevant columns

filtered_df = df[[1,7,8,9,10,11]]
display(filtered_df)

,1,7,8,9,10,11
0,role,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,O,O,1.0426391781948041e-05,12,0.8455598455598455,0.8731182795698925\n
2,O,O,0.2934567630290985,12,0.8455598455598455,0.8731182795698925\n
3,O,O,0.0028503146022558212,12,0.8455598455598455,0.8731182795698925\n
4,O,O,1.510456877440447e-05,12,0.8455598455598455,0.8731182795698925\n
...,...,...,...,...,...,...
14192,O,A,0.8412541747093201,0,0.722007722007722,0.6731182795698925\n
14193,A,O,0.20422163605690002,0,0.722007722007722,0.6731182795698925\n
14194,O,O,0.28565987944602966,0,0.722007722007722,0.6731182795698925\n
14195,S,A,0.9996484518051147,0,0.722007722007722,0.6731182795698925\n
14196,O,O,0.0021522892639040947,0,0.722007722007722,0.6731182795698925\n

In [14]:
## No O roles, only S ones since S A indicates NOM-ACC and SO indicates ERG-ABS

only_S = filtered_df.loc[filtered_df[1] == 'S']
display(only_S)

,1,7,8,9,10,11
9,S,O,0.3000164330005646,12,0.8455598455598455,0.8731182795698925\n
14,S,A,0.713245153427124,12,0.8455598455598455,0.8731182795698925\n
18,S,A,0.9852208495140076,12,0.8455598455598455,0.8731182795698925\n
22,S,A,0.9653986096382141,12,0.8455598455598455,0.8731182795698925\n
23,S,A,0.9980067610740662,12,0.8455598455598455,0.8731182795698925\n
...,...,...,...,...,...,...
14171,S,O,0.02202179655432701,0,0.722007722007722,0.6731182795698925\n
14182,S,O,7.295602699741721e-07,0,0.722007722007722,0.6731182795698925\n
14183,S,O,0.06251595169305801,0,0.722007722007722,0.6731182795698925\n
14188,S,A,0.999995231628418,0,0.722007722007722,0.6731182795698925\n
14195,S,A,0.9996484518051147,0,0.722007722007722,0.6731182795698925\n

In [16]:
## Only S O

obj_col = only_S.loc[only_S[7] == 'O']
display(obj_col)

,1,7,8,9,10,11
9,S,O,0.3000164330005646,12,0.8455598455598455,0.8731182795698925\n
24,S,O,2.8700791517621838e-05,12,0.8455598455598455,0.8731182795698925\n
26,S,O,0.09772969037294388,12,0.8455598455598455,0.8731182795698925\n
37,S,O,0.3664332628250122,12,0.8455598455598455,0.8731182795698925\n
39,S,O,0.015042359940707684,12,0.8455598455598455,0.8731182795698925\n
...,...,...,...,...,...,...
14140,S,O,0.29752546548843384,0,0.722007722007722,0.6731182795698925\n
14163,S,O,0.020570499822497368,0,0.722007722007722,0.6731182795698925\n
14171,S,O,0.02202179655432701,0,0.722007722007722,0.6731182795698925\n
14182,S,O,7.295602699741721e-07,0,0.722007722007722,0.6731182795698925\n
14183,S,O,0.06251595169305801,0,0.722007722007722,0.6731182795698925\n

In [17]:
## Only S A

agent_col = only_S.loc[only_S[7] == 'A']
display(agent_col)

      1  7                   8   9                   10                    11
14     S  A   0.713245153427124  12  0.8455598455598455  0.8731182795698925\n
18     S  A  0.9852208495140076  12  0.8455598455598455  0.8731182795698925\n
22     S  A  0.9653986096382141  12  0.8455598455598455  0.8731182795698925\n
23     S  A  0.9980067610740662  12  0.8455598455598455  0.8731182795698925\n
27     S  A  0.9943320751190186  12  0.8455598455598455  0.8731182795698925\n
...   .. ..                 ...  ..                 ...                   ...
14164  S  A  0.9965682029724121   0   0.722007722007722  0.6731182795698925\n
14165  S  A  0.9999945163726807   0   0.722007722007722  0.6731182795698925\n
14167  S  A  0.6881162524223328   0   0.722007722007722  0.6731182795698925\n
14188  S  A   0.999995231628418   0   0.722007722007722  0.6731182795698925\n
14195  S  A  0.9996484518051147   0   0.722007722007722  0.6731182795698925\n

[2837 rows x 6 columns]

In [30]:
## Only Layer 12 for S O

layer12_obj = obj_col[obj_col[9]== '12']
display(layer12_obj)
display(len(layer12_obj))

,1,7,8,9,10,11
9,S,O,0.3000164330005646,12,0.8455598455598455,0.8731182795698925\n
24,S,O,2.8700791517621838e-05,12,0.8455598455598455,0.8731182795698925\n
26,S,O,0.09772969037294388,12,0.8455598455598455,0.8731182795698925\n
37,S,O,0.3664332628250122,12,0.8455598455598455,0.8731182795698925\n
39,S,O,0.015042359940707684,12,0.8455598455598455,0.8731182795698925\n
57,S,O,0.0017415903275832534,12,0.8455598455598455,0.8731182795698925\n
62,S,O,0.3268545866012573,12,0.8455598455598455,0.8731182795698925\n
63,S,O,0.015152258798480034,12,0.8455598455598455,0.8731182795698925\n
66,S,O,6.218774797162041e-05,12,0.8455598455598455,0.8731182795698925\n
100,S,O,0.2205028086900711,12,0.8455598455598455,0.8731182795698925\n
196,S,O,0.04067963734269142,12,0.8455598455598455,0.8731182795698925\n
207,S,O,0.022319478914141655,12,0.8455598455598455,0.8731182795698925\n
212,S,O,0.4842984974384308,12,0.8455598455598455,0.8731182795698925\n
254,S,O,2.35466586673283e-06,12,0.8455598455598455,0.8731182795698925\n
303,S,O,0.16836915910243988,12,0.8455598455598455,0.8731182795698925\n
348,S,O,0.005342292599380016,12,0.8455598455598455,0.8731182795698925\n
411,S,O,0.14248305559158325,12,0.8455598455598455,0.8731182795698925\n
432,S,O,0.3304615318775177,12,0.8455598455598455,0.8731182795698925\n
481,S,O,0.4674242436885834,12,0.8455598455598455,0.8731182795698925\n
573,S,O,0.23163089156150818,12,0.8455598455598455,0.8731182795698925\n
622,S,O,0.023303091526031494,12,0.8455598455598455,0.8731182795698925\n
643,S,O,0.001377125270664692,12,0.8455598455598455,0.8731182795698925\n
678,S,O,0.031305089592933655,12,0.8455598455598455,0.8731182795698925\n
719,S,O,0.08177835494279861,12,0.8455598455598455,0.8731182795698925\n
736,S,O,8.209911175072193e-05,12,0.8455598455598455,0.8731182795698925\n
753,S,O,0.21009071171283722,12,0.8455598455598455,0.8731182795698925\n
817,S,O,0.03223378583788872,12,0.8455598455598455,0.8731182795698925\n
826,S,O,0.39829888939857483,12,0.8455598455598455,0.8731182795698925\n
864,S,O,0.03431721404194832,12,0.8455598455598455,0.8731182795698925\n
872,S,O,0.38638871908187866,12,0.8455598455598455,0.8731182795698925\n
880,S,O,0.15130147337913513,12,0.8455598455598455,0.8731182795698925\n
891,S,O,4.219752372591756e-05,12,0.8455598455598455,0.8731182795698925\n
954,S,O,0.47270992398262024,12,0.8455598455598455,0.8731182795698925\n
957,S,O,0.11076384782791138,12,0.8455598455598455,0.8731182795698925\n
962,S,O,0.2274373173713684,12,0.8455598455598455,0.8731182795698925\n
987,S,O,0.0536951944231987,12,0.8455598455598455,0.8731182795698925\n
1059,S,O,0.07359083741903305,12,0.8455598455598455,0.8731182795698925\n
1078,S,O,0.1578153818845749,12,0.8455598455598455,0.8731182795698925\n

38

In [48]:
layer12_obj[8] = pd.to_numeric(layer12_obj[8], downcast="float")

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/1508496077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer12_obj[8] = pd.to_numeric(layer12_obj[8], downcast="float")

In [49]:
## Probability_A Average for S O in this layer

layer12_obj[8].mean()

0.14955544

In [31]:
layer11_obj = obj_col[obj_col[9]== '11']
display(layer11_obj)
display(len(layer11_obj))

,1,7,8,9,10,11
1101,S,O,0.01425916887819767,11,0.8803088803088803,0.896774193548387\n
1106,S,O,0.00031804319587536156,11,0.8803088803088803,0.896774193548387\n
1116,S,O,9.373474085805356e-07,11,0.8803088803088803,0.896774193548387\n
1118,S,O,0.19848985970020294,11,0.8803088803088803,0.896774193548387\n
1123,S,O,0.40940189361572266,11,0.8803088803088803,0.896774193548387\n
1131,S,O,0.0002890855830628425,11,0.8803088803088803,0.896774193548387\n
1149,S,O,0.14713922142982483,11,0.8803088803088803,0.896774193548387\n
1155,S,O,1.3588773072115146e-05,11,0.8803088803088803,0.896774193548387\n
1192,S,O,0.010075361467897892,11,0.8803088803088803,0.896774193548387\n
1346,S,O,0.0034017828293144703,11,0.8803088803088803,0.896774193548387\n
1366,S,O,0.042221687734127045,11,0.8803088803088803,0.896774193548387\n
1372,S,O,0.005998282227665186,11,0.8803088803088803,0.896774193548387\n
1395,S,O,0.12158556282520294,11,0.8803088803088803,0.896774193548387\n
1409,S,O,0.3668939769268036,11,0.8803088803088803,0.896774193548387\n
1430,S,O,0.4790865182876587,11,0.8803088803088803,0.896774193548387\n
1452,S,O,0.36091288924217224,11,0.8803088803088803,0.896774193548387\n
1524,S,O,0.09189417213201523,11,0.8803088803088803,0.896774193548387\n
1623,S,O,0.0513496920466423,11,0.8803088803088803,0.896774193548387\n
1714,S,O,0.06447336822748184,11,0.8803088803088803,0.896774193548387\n
1735,S,O,0.023713579401373863,11,0.8803088803088803,0.896774193548387\n
1828,S,O,0.0037686422001570463,11,0.8803088803088803,0.896774193548387\n
1845,S,O,0.024146096780896187,11,0.8803088803088803,0.896774193548387\n
1894,S,O,0.29733067750930786,11,0.8803088803088803,0.896774193548387\n
1956,S,O,0.180166557431221,11,0.8803088803088803,0.896774193548387\n
1964,S,O,0.031125377863645554,11,0.8803088803088803,0.896774193548387\n
1972,S,O,0.2479688674211502,11,0.8803088803088803,0.896774193548387\n
1983,S,O,1.5313468111344264e-06,11,0.8803088803088803,0.896774193548387\n
2038,S,O,0.25814276933670044,11,0.8803088803088803,0.896774193548387\n
2128,S,O,0.2544983923435211,11,0.8803088803088803,0.896774193548387\n
2151,S,O,0.015295017510652542,11,0.8803088803088803,0.896774193548387\n
2170,S,O,4.4566815631696954e-05,11,0.8803088803088803,0.896774193548387\n

31

In [50]:
layer11_obj[8] = pd.to_numeric(layer11_obj[8], downcast="float")
layer11_obj[8].mean()

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2882601234.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer11_obj[8] = pd.to_numeric(layer11_obj[8], downcast="float")

0.119484104

In [51]:
layer12_agent = agent_col[agent_col[9]== '12']
display(layer12_agent)
display(len(layer12_agent))

layer12_agent[8] = pd.to_numeric(layer12_agent[8], downcast="float")
layer12_agent[8].mean()

     1  7                   8   9                   10                    11
14    S  A   0.713245153427124  12  0.8455598455598455  0.8731182795698925\n
18    S  A  0.9852208495140076  12  0.8455598455598455  0.8731182795698925\n
22    S  A  0.9653986096382141  12  0.8455598455598455  0.8731182795698925\n
23    S  A  0.9980067610740662  12  0.8455598455598455  0.8731182795698925\n
27    S  A  0.9943320751190186  12  0.8455598455598455  0.8731182795698925\n
...  .. ..                 ...  ..                 ...                   ...
1063  S  A   0.944007158279419  12  0.8455598455598455  0.8731182795698925\n
1067  S  A  0.9992843270301819  12  0.8455598455598455  0.8731182795698925\n
1079  S  A  0.9999998807907104  12  0.8455598455598455  0.8731182795698925\n
1084  S  A  0.9982582926750183  12  0.8455598455598455  0.8731182795698925\n
1091  S  A  0.9999992847442627  12  0.8455598455598455  0.8731182795698925\n

[242 rows x 6 columns]

242

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/1767855706.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer12_agent[8] = pd.to_numeric(layer12_agent[8], downcast="float")

0.9546398

In [52]:
layer11_agent = agent_col[agent_col[9]== '11']
display(layer11_agent)
display(len(layer11_agent))

layer11_agent[8] = pd.to_numeric(layer11_agent[8], downcast="float")
layer11_agent[8].mean()

     1  7                   8   9                   10                   11
1110  S  A  0.9904875159263611  11  0.8803088803088803  0.896774193548387\n
1114  S  A   0.997572124004364  11  0.8803088803088803  0.896774193548387\n
1115  S  A  0.9956058859825134  11  0.8803088803088803  0.896774193548387\n
1119  S  A  0.9998538494110107  11  0.8803088803088803  0.896774193548387\n
1124  S  A  0.9851989150047302  11  0.8803088803088803  0.896774193548387\n
...  .. ..                 ...  ..                 ...                  ...
2155  S  A  0.9995822310447693  11  0.8803088803088803  0.896774193548387\n
2159  S  A                 1.0  11  0.8803088803088803  0.896774193548387\n
2171  S  A  0.9999665021896362  11  0.8803088803088803  0.896774193548387\n
2176  S  A  0.9999998807907104  11  0.8803088803088803  0.896774193548387\n
2183  S  A  0.9988870024681091  11  0.8803088803088803  0.896774193548387\n

[249 rows x 6 columns]

249

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/855037201.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer11_agent[8] = pd.to_numeric(layer11_agent[8], downcast="float")

0.9723615

In [57]:
layer10_agent = agent_col[agent_col[9]== '10']
#display(layer10_agent)
layer10_agent[8] = pd.to_numeric(layer10_agent[8], downcast="float")
print(layer10_agent[8].mean())

layer9_agent = agent_col[agent_col[9]== '9']
#display(layer9_agent)
layer9_agent[8] = pd.to_numeric(layer9_agent[8], downcast="float")
print(layer9_agent[8].mean())

layer8_agent = agent_col[agent_col[9]== '8']
#display(layer8_agent)
layer8_agent[8] = pd.to_numeric(layer8_agent[8], downcast="float")
print(layer8_agent[8].mean())

layer7_agent = agent_col[agent_col[9]== '7']
#display(layer7_agent)
layer7_agent[8] = pd.to_numeric(layer7_agent[8], downcast="float")
print(layer7_agent[8].mean())

layer6_agent = agent_col[agent_col[9]== '6']
#display(layer6_agent)
layer6_agent[8] = pd.to_numeric(layer6_agent[8], downcast="float")
print(layer6_agent[8].mean())

layer5_agent = agent_col[agent_col[9]== '5']
#display(layer10_agent)
layer5_agent[8] = pd.to_numeric(layer5_agent[8], downcast="float")
print(layer5_agent[8].mean())

layer4_agent = agent_col[agent_col[9]== '4']
#display(layer9_agent)
layer4_agent[8] = pd.to_numeric(layer4_agent[8], downcast="float")
print(layer4_agent[8].mean())

layer3_agent = agent_col[agent_col[9]== '3']
#display(layer8_agent)
layer3_agent[8] = pd.to_numeric(layer3_agent[8], downcast="float")
print(layer3_agent[8].mean())

layer2_agent = agent_col[agent_col[9]== '2']
#display(layer7_agent)
layer2_agent[8] = pd.to_numeric(layer2_agent[8], downcast="float")
print(layer2_agent[8].mean())

layer1_agent = agent_col[agent_col[9]== '1']
#display(layer6_agent)
layer1_agent[8] = pd.to_numeric(layer1_agent[8], downcast="float")
print(layer1_agent[8].mean())

layer0_agent = agent_col[agent_col[9]== '0']
#display(layer6_agent)
layer0_agent[8] = pd.to_numeric(layer0_agent[8], downcast="float")
print(layer0_agent[8].mean())

0.9753772
0.9753988
0.9696649
0.9697346
0.96080565
0.9565658
0.9510143
0.9504868
0.9361084
0.9201356
0.9054044

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer10_agent[8] = pd.to_numeric(layer10_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer9_agent[8] = pd.to_numeric(layer9_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer8_agent[8] = pd.to_numeric(layer8_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer7_agent[8] = pd.to_numeric(layer7_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer6_agent[8] = pd.to_numeric(layer6_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer5_agent[8] = pd.to_numeric(layer5_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer4_agent[8] = pd.to_numeric(layer4_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer3_agent[8] = pd.to_numeric(layer3_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer2_agent[8] = pd.to_numeric(layer2_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer1_agent[8] = pd.to_numeric(layer1_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2654584099.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer0_agent[8] = pd.to_numeric(layer0_agent[8], downcast="float")

In [58]:
layer10_obj = obj_col[obj_col[9]== '10']
#display(layer10_agent)
layer10_obj[8] = pd.to_numeric(layer10_obj[8], downcast="float")
print(layer10_obj[8].mean())

layer9_obj = obj_col[obj_col[9]== '9']
#display(layer9_agent)
layer9_obj[8] = pd.to_numeric(layer9_obj[8], downcast="float")
print(layer9_obj[8].mean())

layer8_obj = obj_col[obj_col[9]== '8']
#display(layer8_agent)
layer8_obj[8] = pd.to_numeric(layer8_obj[8], downcast="float")
print(layer8_obj[8].mean())

layer7_obj = obj_col[obj_col[9]== '7']
#display(layer7_agent)
layer7_obj[8] = pd.to_numeric(layer7_obj[8], downcast="float")
print(layer7_obj[8].mean())

layer6_obj = obj_col[obj_col[9]== '6']
#display(layer6_agent)
layer6_obj[8] = pd.to_numeric(layer6_obj[8], downcast="float")
print(layer6_obj[8].mean())

layer5_obj = obj_col[obj_col[9]== '5']
#display(layer10_agent)
layer5_obj[8] = pd.to_numeric(layer5_obj[8], downcast="float")
print(layer5_obj[8].mean())

layer4_obj = obj_col[obj_col[9]== '4']
#display(layer9_agent)
layer4_obj[8] = pd.to_numeric(layer4_obj[8], downcast="float")
print(layer4_obj[8].mean())

layer3_obj = obj_col[obj_col[9]== '3']
#display(layer8_agent)
layer3_obj[8] = pd.to_numeric(layer3_obj[8], downcast="float")
print(layer3_obj[8].mean())

layer2_obj = obj_col[obj_col[9]== '2']
#display(layer7_agent)
layer2_obj[8] = pd.to_numeric(layer2_obj[8], downcast="float")
print(layer2_obj[8].mean())

layer1_obj = obj_col[obj_col[9]== '1']
#display(layer6_agent)
layer1_obj[8] = pd.to_numeric(layer1_obj[8], downcast="float")
print(layer1_obj[8].mean())

layer0_obj = obj_col[obj_col[9]== '0']
#display(layer6_agent)
layer0_obj[8] = pd.to_numeric(layer0_obj[8], downcast="float")
print(layer0_obj[8].mean())

0.12509334
0.07810015
0.09091076
0.11086419
0.11908341
0.10811018
0.13456807
0.08993283
0.101300105
0.11574273
0.14118996

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer10_obj[8] = pd.to_numeric(layer10_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer9_obj[8] = pd.to_numeric(layer9_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer8_obj[8] = pd.to_numeric(layer8_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer7_obj[8] = pd.to_numeric(layer7_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer6_obj[8] = pd.to_numeric(layer6_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer5_obj[8] = pd.to_numeric(layer5_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer4_obj[8] = pd.to_numeric(layer4_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer3_obj[8] = pd.to_numeric(layer3_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer2_obj[8] = pd.to_numeric(layer2_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer1_obj[8] = pd.to_numeric(layer1_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_39897/2146119274.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer0_obj[8] = pd.to_numeric(layer0_obj[8], downcast="float")