In [343]:
import pandas as pd

In [344]:
with open("ur_udtb-ud_ur_udtb-ud-test.conllu_0", "r", encoding="utf-8") as f:
    read_file = f.readlines()
    print(type(read_file))


df = pd.DataFrame([sub.split(",") for sub in read_file])
display(df)
#df.to_csv("romanian_data.csv", sep=',')

<class 'list'>

,0,1,2,3,4,5,6,7,8,9,10,11
0,,role,case,animacy,subject_word,verb_word,object_word,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,0,A,Acc,,نائیڈو,کر,مکتوب,A,0.9999967813491821,12,0.8825757575757576,0.8375\n
2,1,O,Acc,,,کر,کمشنر,O,0.014298094436526299,12,0.8825757575757576,0.8375\n
3,2,O,Nom,,,کر,مکتوب,O,6.828037840023171e-06,12,0.8825757575757576,0.8375\n
4,3,O,Acc,,,پھیل,بدامنی,O,9.510587551631033e-05,12,0.8825757575757576,0.8375\n
...,...,...,...,...,...,...,...,...,...,...,...,...
14335,14334,O,Nom,,,ہو,عمل,A,0.5645301938056946,0,0.6666666666666666,0.659375\n
14336,14335,O,Nom,,,کر,مشاورت,O,0.3454633355140686,0,0.6666666666666666,0.659375\n
14337,14336,S,Nom,,اجلاس,ہو,,A,0.9099829792976379,0,0.6666666666666666,0.659375\n
14338,14337,O,Acc,,,کر,میکسیکو,O,0.16305339336395264,0,0.6666666666666666,0.659375\n
14339,14338,S,Nom,,انتخابات,ہو,,O,0.00575612997636199,0,0.6666666666666666,0.659375\n

In [345]:
filtered_df = df[[1,7,8,9,10,11]]
display(filtered_df.head(20))

,1,7,8,9,10,11
0,role,predicted_role,probability_A,layer,source_test_accuracy_A,source_test_accuracy_O\n
1,A,A,0.9999967813491821,12,0.8825757575757576,0.8375\n
2,O,O,0.014298094436526299,12,0.8825757575757576,0.8375\n
3,O,O,6.828037840023171e-06,12,0.8825757575757576,0.8375\n
4,O,O,9.510587551631033e-05,12,0.8825757575757576,0.8375\n
5,O,O,0.002103837439790368,12,0.8825757575757576,0.8375\n
6,A,A,0.9999998807907104,12,0.8825757575757576,0.8375\n
7,O,O,0.035874199122190475,12,0.8825757575757576,0.8375\n
8,O,O,0.007645740173757076,12,0.8825757575757576,0.8375\n
9,O,O,0.04281056672334671,12,0.8825757575757576,0.8375\n
10,A,A,1.0,12,0.8825757575757576,0.8375\n
11,S,A,0.996947705745697,12,0.8825757575757576,0.8375\n
12,S,A,0.9999799728393555,12,0.8825757575757576,0.8375\n
13,O,O,3.821270729531534e-05,12,0.8825757575757576,0.8375\n
14,O,O,0.0011873614275828004,12,0.8825757575757576,0.8375\n
15,S,A,0.9982275366783142,12,0.8825757575757576,0.8375\n
16,A,A,0.9999973773956299,12,0.8825757575757576,0.8375\n
17,O,O,0.012680120766162872,12,0.8825757575757576,0.8375\n
18,A,A,0.9937015771865845,12,0.8825757575757576,0.8375\n
19,O,O,0.00037096859887242317,12,0.8825757575757576,0.8375\n

In [346]:
only_S = filtered_df.loc[filtered_df[1] == 'S']
display(only_S)

      1  7                    8   9                   10          11
11     S  A    0.996947705745697  12  0.8825757575757576    0.8375\n
12     S  A   0.9999799728393555  12  0.8825757575757576    0.8375\n
15     S  A   0.9982275366783142  12  0.8825757575757576    0.8375\n
20     S  A   0.5879126191139221  12  0.8825757575757576    0.8375\n
24     S  A   0.7573850750923157  12  0.8825757575757576    0.8375\n
...   .. ..                  ...  ..                 ...         ...
14321  S  O  0.16941285133361816   0  0.6666666666666666  0.659375\n
14323  S  O  0.03346044942736626   0  0.6666666666666666  0.659375\n
14329  S  O  0.03476409986615181   0  0.6666666666666666  0.659375\n
14337  S  A   0.9099829792976379   0  0.6666666666666666  0.659375\n
14339  S  O  0.00575612997636199   0  0.6666666666666666  0.659375\n

[2587 rows x 6 columns]

In [347]:
obj_col = only_S.loc[only_S[7] == 'O']
display(obj_col)

      1  7                       8   9                   10          11
54     S  O     0.04624819755554199  12  0.8825757575757576    0.8375\n
105    S  O     0.34207284450531006  12  0.8825757575757576    0.8375\n
115    S  O     0.34207284450531006  12  0.8825757575757576    0.8375\n
133    S  O  4.7857929530437104e-06  12  0.8825757575757576    0.8375\n
135    S  O   0.0029893547762185335  12  0.8825757575757576    0.8375\n
...   .. ..                     ...  ..                 ...         ...
14316  S  O     0.03873910754919052   0  0.6666666666666666  0.659375\n
14321  S  O     0.16941285133361816   0  0.6666666666666666  0.659375\n
14323  S  O     0.03346044942736626   0  0.6666666666666666  0.659375\n
14329  S  O     0.03476409986615181   0  0.6666666666666666  0.659375\n
14339  S  O     0.00575612997636199   0  0.6666666666666666  0.659375\n

[1143 rows x 6 columns]

In [348]:
agent_col = only_S.loc[only_S[7] == 'A']
display(agent_col)

      1  7                   8   9                   10          11
11     S  A   0.996947705745697  12  0.8825757575757576    0.8375\n
12     S  A  0.9999799728393555  12  0.8825757575757576    0.8375\n
15     S  A  0.9982275366783142  12  0.8825757575757576    0.8375\n
20     S  A  0.5879126191139221  12  0.8825757575757576    0.8375\n
24     S  A  0.7573850750923157  12  0.8825757575757576    0.8375\n
...   .. ..                 ...  ..                 ...         ...
14247  S  A  0.5551126003265381   0  0.6666666666666666  0.659375\n
14287  S  A  0.9847382307052612   0  0.6666666666666666  0.659375\n
14304  S  A  0.8677105903625488   0  0.6666666666666666  0.659375\n
14318  S  A  0.9999114274978638   0  0.6666666666666666  0.659375\n
14337  S  A  0.9099829792976379   0  0.6666666666666666  0.659375\n

[1444 rows x 6 columns]

In [349]:
### Returns the SA and SO averages of Probability A column for each layer

layer12 = only_S[only_S[9]== '12']
#display(layer12)
layer12[8] = pd.to_numeric(layer12[8], downcast="float")
print(layer12[8].mean())

layer11 = only_S[only_S[9]== '11']
#display(layer11)
layer11[8] = pd.to_numeric(layer11[8], downcast="float")
print(layer11[8].mean())

layer10 = only_S[only_S[9]== '10']
#display(layer10)
layer10[8] = pd.to_numeric(layer10[8], downcast="float")
print(layer10[8].mean())

layer9 = only_S[only_S[9]== '9']
#display(layer9)
layer9[8] = pd.to_numeric(layer9[8], downcast="float")
print(layer9[8].mean())

layer8 = only_S[only_S[9]== '8']
#display(layer8)
layer8[8] = pd.to_numeric(layer8[8], downcast="float")
print(layer8[8].mean())

layer7 = only_S[only_S[9]== '7']
#display(layer7)
layer7[8] = pd.to_numeric(layer7[8], downcast="float")
print(layer7[8].mean())

layer6 = only_S[only_S[9]== '6']
#display(layer6)
layer6[8] = pd.to_numeric(layer6[8], downcast="float")
print(layer6[8].mean())

layer5 = only_S[only_S[9]== '5']
#display(layer10)
layer5[8] = pd.to_numeric(layer5[8], downcast="float")
print(layer5[8].mean())

layer4 = only_S[only_S[9]== '4']
#display(layer9)
layer4[8] = pd.to_numeric(layer4[8], downcast="float")
print(layer4[8].mean())

layer3 = only_S[only_S[9]== '3']
#display(layer8)
layer3[8] = pd.to_numeric(layer3[8], downcast="float")
print(layer3[8].mean())

layer2 = only_S[only_S[9]== '2']
#display(layer7)
layer2[8] = pd.to_numeric(layer2[8], downcast="float")
print(layer2[8].mean())

layer1 = only_S[only_S[9]== '1']
#display(layer6)
layer1[8] = pd.to_numeric(layer1[8], downcast="float")
print(layer1[8].mean())

layer0 = only_S[only_S[9]== '0']
#display(layer6)
layer0[8] = pd.to_numeric(layer0[8], downcast="float")
print(layer0[8].mean())

0.6206137
0.63120645
0.62755966
0.65000594
0.62664175
0.6375134
0.578537
0.5469084
0.47945967
0.50038314
0.47355515
0.42220518
0.4905001

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer12[8] = pd.to_numeric(layer12[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer11[8] = pd.to_numeric(layer11[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer10[8] = pd.to_numeric(layer10[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer9[8] = pd.to_numeric(layer9[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer8[8] = pd.to_numeric(layer8[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer7[8] = pd.to_numeric(layer7[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer6[8] = pd.to_numeric(layer6[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer5[8] = pd.to_numeric(layer5[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer4[8] = pd.to_numeric(layer4[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer3[8] = pd.to_numeric(layer3[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer2[8] = pd.to_numeric(layer2[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer1[8] = pd.to_numeric(layer1[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/1109710783.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer0[8] = pd.to_numeric(layer0[8], downcast="float")

In [350]:
### Returns the SA averages of Probability A column for each layer

layer12_agent = agent_col[agent_col[9]== '12']
#display(layer12_agent)
layer12_agent[8] = pd.to_numeric(layer12_agent[8], downcast="float")
print(layer12_agent[8].mean())

layer11_agent = agent_col[agent_col[9]== '11']
#display(layer11_agent)
layer11_agent[8] = pd.to_numeric(layer11_agent[8], downcast="float")
print(layer11_agent[8].mean())

layer10_agent = agent_col[agent_col[9]== '10']
#display(layer10_agent)
layer10_agent[8] = pd.to_numeric(layer10_agent[8], downcast="float")
print(layer10_agent[8].mean())

layer9_agent = agent_col[agent_col[9]== '9']
#display(layer9_agent)
layer9_agent[8] = pd.to_numeric(layer9_agent[8], downcast="float")
print(layer9_agent[8].mean())

layer8_agent = agent_col[agent_col[9]== '8']
#display(layer8_agent)
layer8_agent[8] = pd.to_numeric(layer8_agent[8], downcast="float")
print(layer8_agent[8].mean())

layer7_agent = agent_col[agent_col[9]== '7']
#display(layer7_agent)
layer7_agent[8] = pd.to_numeric(layer7_agent[8], downcast="float")
print(layer7_agent[8].mean())

layer6_agent = agent_col[agent_col[9]== '6']
#display(layer6_agent)
layer6_agent[8] = pd.to_numeric(layer6_agent[8], downcast="float")
print(layer6_agent[8].mean())

layer5_agent = agent_col[agent_col[9]== '5']
#display(layer10_agent)
layer5_agent[8] = pd.to_numeric(layer5_agent[8], downcast="float")
print(layer5_agent[8].mean())

layer4_agent = agent_col[agent_col[9]== '4']
#display(layer9_agent)
layer4_agent[8] = pd.to_numeric(layer4_agent[8], downcast="float")
print(layer4_agent[8].mean())

layer3_agent = agent_col[agent_col[9]== '3']
#display(layer8_agent)
layer3_agent[8] = pd.to_numeric(layer3_agent[8], downcast="float")
print(layer3_agent[8].mean())

layer2_agent = agent_col[agent_col[9]== '2']
#display(layer7_agent)
layer2_agent[8] = pd.to_numeric(layer2_agent[8], downcast="float")
print(layer2_agent[8].mean())

layer1_agent = agent_col[agent_col[9]== '1']
#display(layer6_agent)
layer1_agent[8] = pd.to_numeric(layer1_agent[8], downcast="float")
print(layer1_agent[8].mean())

layer0_agent = agent_col[agent_col[9]== '0']
#display(layer6_agent)
layer0_agent[8] = pd.to_numeric(layer0_agent[8], downcast="float")
print(layer0_agent[8].mean())

0.94873214
0.94096833
0.9372721
0.95423347
0.9472396
0.96162134
0.9534972
0.9293546
0.9139908
0.91218185
0.86639804
0.8562891
0.8037861

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer12_agent[8] = pd.to_numeric(layer12_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer11_agent[8] = pd.to_numeric(layer11_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer10_agent[8] = pd.to_numeric(layer10_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer9_agent[8] = pd.to_numeric(layer9_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer8_agent[8] = pd.to_numeric(layer8_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer7_agent[8] = pd.to_numeric(layer7_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer6_agent[8] = pd.to_numeric(layer6_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer5_agent[8] = pd.to_numeric(layer5_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer4_agent[8] = pd.to_numeric(layer4_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer3_agent[8] = pd.to_numeric(layer3_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer2_agent[8] = pd.to_numeric(layer2_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer1_agent[8] = pd.to_numeric(layer1_agent[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/770741630.py:65: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer0_agent[8] = pd.to_numeric(layer0_agent[8], downcast="float")

In [351]:
### Returns the SO averages of Probability A column for each layer


layer12_obj = obj_col[obj_col[9]== '12']
#display(layer12_obj)
layer12_obj[8] = pd.to_numeric(layer12_obj[8], downcast="float")
print(layer12_obj[8].mean())

layer11_obj = obj_col[obj_col[9]== '11']
#display(layer11_obj)
layer11_obj[8] = pd.to_numeric(layer11_obj[8], downcast="float")
print(layer11_obj[8].mean())

layer10_obj = obj_col[obj_col[9]== '10']
#display(layer10_agent)
layer10_obj[8] = pd.to_numeric(layer10_obj[8], downcast="float")
print(layer10_obj[8].mean())

layer9_obj = obj_col[obj_col[9]== '9']
#display(layer9_agent)
layer9_obj[8] = pd.to_numeric(layer9_obj[8], downcast="float")
print(layer9_obj[8].mean())

layer8_obj = obj_col[obj_col[9]== '8']
#display(layer8_agent)
layer8_obj[8] = pd.to_numeric(layer8_obj[8], downcast="float")
print(layer8_obj[8].mean())

layer7_obj = obj_col[obj_col[9]== '7']
#display(layer7_agent)
layer7_obj[8] = pd.to_numeric(layer7_obj[8], downcast="float")
print(layer7_obj[8].mean())

layer6_obj = obj_col[obj_col[9]== '6']
#display(layer6_agent)
layer6_obj[8] = pd.to_numeric(layer6_obj[8], downcast="float")
print(layer6_obj[8].mean())

layer5_obj = obj_col[obj_col[9]== '5']
#display(layer10_agent)
layer5_obj[8] = pd.to_numeric(layer5_obj[8], downcast="float")
print(layer5_obj[8].mean())

layer4_obj = obj_col[obj_col[9]== '4']
#display(layer9_agent)
layer4_obj[8] = pd.to_numeric(layer4_obj[8], downcast="float")
print(layer4_obj[8].mean())

layer3_obj = obj_col[obj_col[9]== '3']
#display(layer8_agent)
layer3_obj[8] = pd.to_numeric(layer3_obj[8], downcast="float")
print(layer3_obj[8].mean())

layer2_obj = obj_col[obj_col[9]== '2']
#display(layer7_agent)
layer2_obj[8] = pd.to_numeric(layer2_obj[8], downcast="float")
print(layer2_obj[8].mean())

layer1_obj = obj_col[obj_col[9]== '1']
#display(layer6_agent)
layer1_obj[8] = pd.to_numeric(layer1_obj[8], downcast="float")
print(layer1_obj[8].mean())

layer0_obj = obj_col[obj_col[9]== '0']
#display(layer6_agent)
layer0_obj[8] = pd.to_numeric(layer0_obj[8], downcast="float")
print(layer0_obj[8].mean())

0.08957989
0.07276245
0.081261426
0.050632246
0.08509134
0.090033665
0.054496318
0.06450453
0.08253241
0.11657083
0.12889096
0.16522744
0.18034701

/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer12_obj[8] = pd.to_numeric(layer12_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer11_obj[8] = pd.to_numeric(layer11_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer10_obj[8] = pd.to_numeric(layer10_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer9_obj[8] = pd.to_numeric(layer9_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer8_obj[8] = pd.to_numeric(layer8_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer7_obj[8] = pd.to_numeric(layer7_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer6_obj[8] = pd.to_numeric(layer6_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer5_obj[8] = pd.to_numeric(layer5_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer4_obj[8] = pd.to_numeric(layer4_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer3_obj[8] = pd.to_numeric(layer3_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer2_obj[8] = pd.to_numeric(layer2_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:61: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer1_obj[8] = pd.to_numeric(layer1_obj[8], downcast="float")
/var/folders/49/431zj7ys6_n42jcfj9z6ycb80000gn/T/ipykernel_25692/730305013.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  layer0_obj[8] = pd.to_numeric(layer0_obj[8], downcast="float")